#
# Conifer build process for Travis CI
#


language: node

# For now, just get lando running...
matrix:
  include:
    - name: 'End-to-end tests with Lando/Cypress'
      language: node_js
      node_js: 10
      cache:
        - ~/.lando
        - ~/.cache
      before_install:
        - sudo apt-get -y update
        - sudo apt-get -y install cgroup-bin curl
        - curl -fsSL -o /tmp/lando-latest.deb https://github.com/lando/lando/releases/download/v3.0.0-rc.1/lando-v3.0.0-rc.1.deb
        - sudo dpkg -i /tmp/lando-latest.deb
        - lando version
      install:
        - lando start
        - lando yarn --frozen-lockfile
        - lando webpack
      script:
        # TODO run tests
        - lando version
      #after_failure:
      #- curl --upload-file ./cypress/videos/conifer.spec.js.mp4 https://transfer.sh/conifer.spec.js.mp4

